#!/usr/bin/env ruby -w

require 'rake'

# A helper function for answering: Does this spec run fast?
module Fast
  module_function
  def spec?(fn)
    open(fn) { |f| f.gets =~ /fast_helper/ }
  end
end

fast_specs = FileList['spec/**/*_spec.rb'].select do |fn|
  Fast.spec?(fn)
end

if fast_specs.any?
  system "rspec #{fast_specs}"
else
  puts 'Unable to find any fast specs'
  exit(-1)
end
